apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  namespace: default
  labels:
    app: ftps-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftps-port-20
        - containerPort: 21
          name: ftps-port-21
        - containerPort: 20000
          name: ftps-port-20000
        volumeMounts:
          - mountPath: /home
            name: ftps-persistent-volume
        env:
        - name: FTP_USER
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: ftp-user
        - name: FTP_PASSWD
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: ftp-passwd
        - name: IP
          value: 192.168.49.2
      volumes:
       - name: ftps-persistent-volume
         persistentVolumeClaim:
          claimName: ftps-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.49.2
  ports:
  - port: 20
    name: ftps-port-20
    targetPort: 20
    protocol: TCP
  - port: 21
    name: ftps-port-21
    targetPort: 21
    protocol: TCP
  - port: 20000
    name: ftps-port-20000
    targetPort: 20000
    protocol: TCP
